[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins","alloc"]
[build]
target = "x86_64-os_in_rust.json"
[target.'cfg(target_os = "none")']
runner ="bootimage runner"